"""auto_stage_discovered_cells — wire the Universal Walk-Forward output
to live_allowlist as shadow_only candidates.

User direction 2026-05-17: complete the Universal Shadow Discovery
Pipeline — discoveries should auto-stage to shadow_trades for further
validation, not just sit in a report.

Method:
  1. Read state/strategy_validation_universal.json (produced by
     scripts/universal_walk_forward.py)
  2. For each graduation_eligible cell NOT already in live_allowlist,
     add it as shadow_only=True + experimental=True + broker='topstep'
  3. Discoveries gather shadow trades via existing brain_signaler
     pathway. After 2 weeks of n>=25 + t>=2.0 in shadow, eligible for
     promotion review.

Output:
  - state/strategy_validation.json updated (with .bak backup)
  - vault/research/analysis/<date>_auto_staged_discoveries.md report

Safety:
  - Only stages cells flagged graduation_eligible in the universal sweep
  - Re-running is idempotent (already-staged cells skipped)
  - Cells are shadow_only — they NEVER auto-fire live, regardless of
    graduation score
  - Full backup before write
"""
from __future__ import annotations

import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ALLOWLIST_PATH = ROOT / "state" / "strategy_validation.json"
# 2026-05-17 fix: universal_walk_forward.py writes to
# state/universal_walkforward_results.json, NOT
# strategy_validation_universal.json. Filename mismatch caused the
# chain to silently abort on first auto-stage run.
UNIVERSAL_PATH = ROOT / "state" / "universal_walkforward_results.json"
REPORT_DIR = ROOT / "vault" / "research" / "analysis"


def cell_key(c: dict) -> tuple:
    return (c.get("symbol", ""), c.get("strategy", ""),
            c.get("session", ""), c.get("side", ""))


def main() -> int:
    if not ALLOWLIST_PATH.exists():
        print(f"ABORT: {ALLOWLIST_PATH} missing")
        return 2
    if not UNIVERSAL_PATH.exists():
        print(f"ABORT: {UNIVERSAL_PATH} missing — run "
              f"scripts/universal_walk_forward.py first")
        return 2

    with ALLOWLIST_PATH.open() as f:
        allow_data = json.load(f)
    cells = allow_data.get("live_allowlist", [])
    existing_keys = {cell_key(c) for c in cells}

    with UNIVERSAL_PATH.open() as f:
        univ = json.load(f)
    all_cells = univ.get("cells_all", [])
    # 2026-05-17 Pattern A defense: graduation_eligible can serialize as
    # str("True"/"False") OR native bool from the upstream sweep (default=str
    # in json.dump on numpy.bool_). String "False" is TRUTHY in Python and
    # silently staged 1622 false-positive cells. Coerce explicitly.
    def _is_eligible(c):
        v = c.get("graduation_eligible")
        if isinstance(v, bool):
            return v
        if isinstance(v, str):
            return v.strip().lower() == "true"
        return bool(v)
    eligible = [c for c in all_cells if _is_eligible(c)]

    today = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    backup = ALLOWLIST_PATH.with_suffix(f".json.bak_autostage_{today}")
    shutil.copy(ALLOWLIST_PATH, backup)

    staged: list[dict] = []
    skipped_existing: list[tuple] = []
    for c in eligible:
        key = cell_key(c)
        if key in existing_keys:
            skipped_existing.append(key)
            continue
        new_cell = {
            "symbol": c["symbol"],
            "strategy": c["strategy"],
            "session": c["session"],
            "side": c["side"],
            "broker": "topstep",
            "experimental": True,
            "shadow_only": True,
            "regime_filter": {},
            "added": today,
            "source": "universal_walk_forward_autostage",
            "discovery_n": c.get("oos_n"),
            "discovery_t": c.get("oos_t"),
            "discovery_E": c.get("oos_E"),
        }
        staged.append(new_cell)

    if not staged:
        print(f"No new graduation-eligible cells to stage. "
              f"Existing: {len(existing_keys)}, Eligible: {len(eligible)}")
        return 0

    # Apply
    allow_data["live_allowlist"] = cells + staged
    allow_data["last_autostage"] = today
    with ALLOWLIST_PATH.open("w", encoding="utf-8") as f:
        json.dump(allow_data, f, indent=2, default=str)

    # Report
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / f"{today}_auto_staged_discoveries.md"
    lines = [
        "---", "type: analysis", f"date: {today}",
        "purpose: Auto-staged discoveries from Universal Walk-Forward",
        "---", "",
        "# Auto-staged discoveries — Universal Walk-Forward",
        "",
        f"Generated by `scripts/auto_stage_discovered_cells.py`.",
        f"",
        f"## Summary",
        f"- Universal sweep generated at: {univ.get('generated_at')}",
        f"- Graduation-eligible cells found: **{len(eligible)}**",
        f"- Already in allowlist (skipped): **{len(skipped_existing)}**",
        f"- Newly staged (shadow_only=True): **{len(staged)}**",
        f"- Backup: `{backup.name}`",
        "",
        "## Newly staged cells",
        "",
        "| Symbol | Strategy | Session | Side | n | t | E |",
        "|---|---|---|---|---|---|---|",
    ]
    for c in staged:
        lines.append(
            f"| {c['symbol']} | {c['strategy']} | {c['session']} | "
            f"{c['side']} | {c.get('discovery_n')} | "
            f"{c.get('discovery_t')} | {c.get('discovery_E')} |"
        )
    lines += [
        "",
        "## Promotion criteria",
        "",
        "These cells fire only through the shadow pathway. Track for 2",
        "weeks. Promote (set `shadow_only=False`) when:",
        "- n >= 25 shadow trades resolved",
        "- t-stat >= 2.0 in shadow",
        "- E > 0 (after exec_mirror friction)",
        "",
        "Until promotion criteria are met, these add ZERO real-money risk.",
    ]
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Staged {len(staged)} new cells")
    print(f"Report: {report_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
