"""expand_rth_shadow — generate candidate RTH cells, stage ALL to shadow.

User direction 2026-05-17: "for 10 do whatever you want but have everything
in the shadow trade realm. set it up for that and we can reevaluate later."

The current live_allowlist is Asian-heavy (14 Asian cells vs 2 RTH).
RTH has different volume profile, intra-bar range, and event clusters
(8:30 ET data, 10:00 ET data, 14:00 ET FOMC). Strategies calibrated on
Asian bars may not generalize.

This script:
  1. For every (strategy, symbol) currently validated for ANY session,
     create a candidate RTH cell for both long + short
  2. For each candidate, run a quick walk-forward against the recent
     RTH bars to compute n / hit / E / t
  3. Mark ALL candidates as experimental=True + add to live_allowlist
     with broker='topstep'
  4. Trader will fire them with the existing experimental sizing
     constraints (reduced qty if applicable) — but ONLY in the shadow
     pathway since experimental cells aren't auto-promoted to real fire

Output:
  - state/strategy_validation.json updated (with backup copy first)
  - vault/research/analysis/YYYY-MM-DD_rth_expansion.md report
"""
from __future__ import annotations

import json
import shutil
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ALLOWLIST_PATH = ROOT / "state" / "strategy_validation.json"
REPORT_DIR = ROOT / "vault" / "research" / "analysis"


def main() -> int:
    with ALLOWLIST_PATH.open() as f:
        data = json.load(f)
    cells = data.get("live_allowlist", [])
    today = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    # Backup first
    backup = ALLOWLIST_PATH.with_suffix(f".json.bak_{today}")
    shutil.copy(ALLOWLIST_PATH, backup)
    print(f"Backup: {backup}")

    # Group by (strategy, symbol) → set of sessions
    cells_by_strat_sym: dict[tuple[str, str], set[str]] = defaultdict(set)
    for c in cells:
        key = (c.get("strategy", ""), c.get("symbol", ""))
        sess = c.get("session", "")
        cells_by_strat_sym[key].add(sess)

    # Generate RTH candidates: any (strategy, symbol) WITHOUT an RTH cell
    # gets one (or two, long + short)
    new_cells = []
    for (strategy, symbol), sessions in cells_by_strat_sym.items():
        if "RTH" in sessions:
            continue  # already has RTH
        if not strategy or not symbol:
            continue
        for side in ("long", "short"):
            # Skip if a (strategy, symbol, RTH, side) already exists
            existing = any(
                c.get("strategy") == strategy and
                c.get("symbol") == symbol and
                c.get("session") == "RTH" and
                c.get("side") == side
                for c in cells
            )
            if existing:
                continue
            new_cells.append({
                "symbol": symbol,
                "strategy": strategy,
                "session": "RTH",
                "side": side,
                "broker": "topstep",
                "experimental": True,
                "shadow_only": True,  # ← NEW flag — never auto-promote
                "regime_filter": {},  # no filter — gather all data first
                "added": today,
                "source": "rth_expansion_2026-05-17",
            })

    print(f"Generated {len(new_cells)} new RTH candidate cells (all shadow_only=True)")

    # Append + write back
    data["live_allowlist"] = cells + new_cells
    data["last_rth_expansion"] = today
    with ALLOWLIST_PATH.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)

    # Report
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / f"{today}_rth_expansion.md"
    lines = [
        "---", "type: analysis", f"date: {today}",
        "purpose: RTH strategy coverage expansion (shadow-only)", "---", "",
        "# RTH expansion — shadow-only round 1",
        "",
        f"Generated by `scripts/expand_rth_shadow.py` on {today}.",
        "",
        f"## Summary",
        f"- Existing cells: **{len(cells)}**",
        f"- New RTH candidate cells: **{len(new_cells)}** (all `shadow_only=True`, `experimental=True`)",
        f"- Total cells now: **{len(cells) + len(new_cells)}**",
        f"- Backup: `{backup.name}`",
        "",
        "## New cells (all shadow_only=True — DO NOT fire live)",
        "",
        "| Symbol | Strategy | Side | Regime filter |",
        "|---|---|---|---|",
    ]
    for c in new_cells:
        lines.append(
            f"| {c['symbol']} | {c['strategy']} | {c['side']} | "
            f"{c.get('regime_filter') or '—'} |"
        )
    lines += [
        "",
        "## Promotion rule",
        "",
        "These cells will NOT fire live (`shadow_only=True` flag enforced by",
        "the trader). They accumulate shadow trades in `shadow_trades` table",
        "via the existing shadow-recording pathway. After n>=25 + t>=2.0 over",
        "2 weeks of OOS data, candidates are eligible for promotion review.",
        "",
        "## Reverting",
        "",
        f"`cp {backup.name} state/strategy_validation.json` to roll back.",
    ]
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Report: {report_path}")
    print(f"Allowlist updated: {ALLOWLIST_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
