"""Nightly orchestrator — runs all end-of-day reports + maintenance.

Sequence:
  1. resolve_shadow_trades  (final pass on today's signals)
  2. shadow_trade_recap     (GREEN/YELLOW/RED candidate report)
  3. pnl_attribution        (which strategies/symbols paid)
  4. simulated_equity_curve (real vs real+shadow)
  5. agent_scorecards       (rolling perf + calibration)
  6. auto_promote_lessons   (RULE-tier lessons → blacklist)
  7. build_economic_calendar (tomorrow's high-impact events)

Each step is best-effort — a failure in one doesn't stop the others.
Output: vault/_meta/nightly_run_YYYY-MM-DD.md (run summary).

Costs: zero Claude API usage. All scripts read SQLite + ProjectX bars
+ filesystem. Safe to run unattended.

Usage:
  python -m scripts.nightly_reports
"""
from __future__ import annotations

import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


LOG_DIR = Path("vault/_meta")


STEPS: list[tuple[str, list[str], int]] = [
    # (label, argv, timeout_seconds)
    ("resolve_shadow_trades",
     [sys.executable, "-m", "scripts.resolve_shadow_trades",
      "--min-age", "0", "--limit", "500"], 600),
    ("shadow_trade_recap",
     [sys.executable, "-m", "scripts.shadow_trade_recap",
      "--days", "14", "--quiet"], 60),
    ("pnl_attribution",
     [sys.executable, "-m", "scripts.pnl_attribution",
      "--days", "30", "--quiet"], 60),
    ("simulated_equity_curve",
     [sys.executable, "-m", "scripts.simulated_equity_curve",
      "--days", "30", "--quiet"], 60),
    ("agent_scorecards",
     [sys.executable, "-m", "scripts.agent_scorecards",
      "--window", "100", "--quiet"], 60),
    ("auto_promote_lessons",
     [sys.executable, "-m", "scripts.auto_promote_lessons",
      "--quiet"], 30),
    ("build_economic_calendar",
     [sys.executable, "-m", "scripts.build_economic_calendar",
      "--days", "2", "--quiet"], 30),
]


def main() -> int:
    started = datetime.now(tz=timezone.utc)
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_path = LOG_DIR / f"nightly_run_{started.strftime('%Y-%m-%d')}.md"
    lines = [f"# Nightly Run — {started.strftime('%Y-%m-%d %H:%M UTC')}",
             "", "| Step | Status | Duration | Notes |",
             "|---|:---:|---:|---|"]
    overall_ok = True
    for label, argv, timeout in STEPS:
        t0 = time.monotonic()
        status = "ok"
        notes = ""
        try:
            r = subprocess.run(argv, capture_output=True, text=True,
                               timeout=timeout)
            if r.returncode != 0:
                status = "fail"
                overall_ok = False
                notes = (r.stderr or r.stdout or "").splitlines()
                notes = notes[-1] if notes else f"exit={r.returncode}"
                notes = notes[:120].replace("|", "/")
        except subprocess.TimeoutExpired:
            status = "timeout"
            overall_ok = False
            notes = f"exceeded {timeout}s"
        except Exception as e:
            status = "error"
            overall_ok = False
            notes = str(e)[:120].replace("|", "/")
        dt = time.monotonic() - t0
        lines.append(f"| {label} | {status} | {dt:.1f}s | {notes} |")
        print(f"[{status:7s}] {label:30s} {dt:6.1f}s  {notes}")

    lines += ["", f"**Overall:** {'✓ all green' if overall_ok else '✗ failures present'}",
              "", f"_Generated by `scripts/nightly_reports.py`._"]
    log_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote: {log_path}")
    return 0 if overall_ok else 1


if __name__ == "__main__":
    sys.exit(main())
